stages:
  - build
  - test
  - deploy

variables:
  IMAGE: golang:1.16
  GCLOUD_PROJECT_ID: myika-anastasia

api-build:
  stage: build
  only:
    - production
  image: $IMAGE
  script:
    - go build

# api-unit-test:
#   stage: test
#   only:
#     - master
#     - production
#   image: $IMAGE
#   script:
#     - go test

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCLOUD_KEY
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCLOUD_PROJECT_ID/strategy-svc-$CI_COMMIT_SHORT_SHA
    - gcloud beta run deploy strategy-svc --image gcr.io/$GCLOUD_PROJECT_ID/strategy-svc-$CI_COMMIT_SHORT_SHA --port 8000 --platform managed --min-instances 2 --max-instances 5 --allow-unauthenticated --region asia-southeast1 --memory 128Mi --cpu 1 --concurrency 10 --timeout 1000 --vpc-connector redis-streams --set-env-vars REDISHOST_MSNGR=$REDISHOST_MSNGR,REDISPORT_MSNGR=$REDISPORT_MSNGR,REDISPASS_MSNGR=$REDISPASS_MSNGR,REDISHOST_CM=$REDISHOST_CM,REDISPORT_CM=$REDISPORT_CM,REDISPASS_CM=$REDISPASS_CM
