stages:
  - build
  # - test
  - deploy

variables:
  IMAGE: golang:1.16
  GCLOUD_PROJECT_ID: myika-anastasia

api-build:
  stage: build
  only:
    - master
  image: $IMAGE
  script:
    - go build

# unit-test:
#   stage: test
#   only:
#     - master
#   image: $IMAGE
#   script:
#     - go test
